### ISSUE TITLE
TypeError: Cannot set property 'fillStyle' of null

### ISSUE THREAD

**Issue by akshay-kochhar** [felippenardi/lottie-react-web#21]
Getting this error for all the test cases when they try to mount the component using enzyme.
It shows error corresponding to the import line "**import Lottie from 'lottie-react-web';**"

**Comment by RonnyO** [comment]
Installing and setting up https://www.npmjs.com/package/jest-canvas-mock worked for me

**Comment by hutber** [comment]
Its a shame you can't easlier to use with create-react-app though

**Comment by koriner** [comment]
@hutber You can use it with CRA

I just added `require('jest-canvas-mock');` to the top of my `setupTests.js` file :)

**Comment by ICeZer0** [comment]
Is there another fix for this? My test suite is AVA?

**Comment by namlq93** [comment]
I've got error like this issue when run test. I've set config like above and it worked. But I've got new error: `Error: connect ECONNREFUSED 127.0.0.1:80` :( 

![Screen Shot 2020-04-29 at 10 09 21](https://user-images.githubusercontent.com/41458989/80561949-5c3f8d00-8a10-11ea-89af-04ed6f85653c.png)

![Screen Shot 2020-04-29 at 10 10 47](https://user-images.githubusercontent.com/41458989/80561956-62356e00-8a10-11ea-92e5-d7d1f172bd3d.png)

**Comment by namlq93** [comment]
> Installing and setting up https://www.npmjs.com/package/jest-canvas-mock worked for me

I've got error like this issue when run test. I've set config jest-canvas-mock and it worked. But I've got new error: `Error: connect ECONNREFUSED 127.0.0.1:80` :( 

![Screen Shot 2020-04-29 at 10 09 21](https://user-images.githubusercontent.com/41458989/80561949-5c3f8d00-8a10-11ea-89af-04ed6f85653c.png)

![Screen Shot 2020-04-29 at 10 10 47](https://user-images.githubusercontent.com/41458989/80561956-62356e00-8a10-11ea-92e5-d7d1f172bd3d.png)

**Comment by ICeZer0** [comment]
For those of us not using jest, my fix was to install `canvas` and `JSDOM`  then mock the canvas

**Comment by AshishKapoor** [comment]
> Installing and setting up https://www.npmjs.com/package/jest-canvas-mock worked for me

Also

```$ yarn install canvas```

**Comment by nk250319** [comment]
> @hutber You can use it with CRA
> 
> I just added `require('jest-canvas-mock');` to the top of my `setupTests.js` file :)

This totally worked for me. Thanks!!

**Comment by mlenser** [comment]
A better way is to setup jest to handle this. `jest.config.js`:
```
module.exports = {
  setupFilesAfterEnv: ['jest-canvas-mock'],
};
```

**Comment by bidva** [comment]
I still have the issue 
my app is created by react-app-rewired 
I have setup canvas-mock on package.json
```
"jest": {
    "setupFiles": [
      "<rootDir>/src/setupTests.js",
      "jest-canvas-mock"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!src/**/*.d.ts"
    ]
  },
````

also imported that top of my setupTests.js as well 

```
import 'jest-canvas-mock';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });

// Included to mock local storage in JS tests, see docs at
// https://www.npmjs.com/package/jest-localstorage-mock#in-create-react-app

require('jest-localstorage-mock');
// for plotly.js to work
//
window.URL.createObjectURL = function createObjectURL() {};
// to fix Error: Not implemented: HTMLCanvasElement.prototype.getContext
window.HTMLCanvasElement.prototype.getContext = () => {}; 
```

but getting:

```
TypeError: Cannot set property 'fillStyle' of undefined

    > 1 | import { Player } from '@lottiefiles/react-lottie-player';
        | ^
      2 | import projection_replay from '../assets/lottie/projection_replay.json';
      3 |
      4 | const ProjectionNotReady = () => {

      at canvas (node_modules/@lottiefiles/react-lottie-player/node_modules/lottie-web/build/player/lottie.js:4699:9)
      at ImagePreloaderFactory (node_modules/@lottiefiles/react-lottie-player/node_modules/lottie-web/build/player/lottie.js:4701:12)
      at factory (node_modules/@lottiefiles/react-lottie-player/node_modules/lottie-web/build/player/lottie.js:4897:10)
      at lottie (node_modules/@lottiefiles/react-lottie-player/node_modules/lottie-web/build/player/lottie.js:7:26)
      at value (node_modules/@lottiefiles/react-lottie-player/node_modules/lottie-web/build/player/lottie.js:10:31)
      at value (node_modules/@lottiefiles/react-lottie-player/node_modules/tslib/tslib.es6.js:234:105)
      at Object.<anonymous> (node_modules/@lottiefiles/react-lottie-player/node_modules/tslib/tslib.es6.js:234:105)
      at Object.<anonymous> (src/components/ProjectionNotReady.js:1:1)
      at Object.<anonymous> (src/containers/Home/Models/Model.js:37:1)
      at Object.<anonymous> (src/containers/Home/Models/Models.js:27:1)
      at Object.<anonymous> (src/containers/Home/Home.js:10:1)
      at Object.<anonymous> (src/containers/Home/index.js:1:1)
      at Object.<anonymous> (src/containers/index.js:1:1)
      at Object.<anonymous> (src/Routes.jsx:4:1)
      at Object.<anonymous> (src/App.js:2:1)
      at Object.<anonymous> (src/App.test.js:3:1)
```
any idea?

**Comment by bidva** [comment]
just for others, adding to import to existed setupTest.js didn't work for me but adding it to a new file worked. it's a bit strange but just said.

**Comment by MagnusHJensen** [comment]
Any updates on this?

doing the `require('jest-canvas-mock');` at the top of `setupTests.ts` file worked fine, but It would be nice to not include a third-party lib just to use lottie.

**Comment by aquibbaig** [comment]
none of the above mentioned solutions work for me.
```
 TypeError: Cannot set properties of null (setting 'fillStyle')

      1 | import animationData from 'assets/lotties/paperplane.json';
      2 | import { useAuth } from 'hooks/useAuth';
    > 3 | import Lottie from 'lottie-react';
```

have installed `jest-canvas-mock` as devDep & have imported on top of `setupTests.ts`.
i am using CRA with default `react-scripts`

**Comment by fahmij8** [comment]
This is my current solution. While I'm trying to import `jest-canvas-mock` in my `setupTests` file, I also do this in the error test file : 

```
// Mock the CanvasRenderingContext2D object
class CanvasRenderingContext2DMock {
  fillStyle = '';
  fillRect = jest.fn();
  // Add any other necessary properties and methods
}

// Set up the mock before running the tests
beforeEach(() => {
  // @ts-ignore
  window.HTMLCanvasElement.prototype.getContext = () => {
    return new CanvasRenderingContext2DMock();
  };
});

// Now you can run your tests without encountering the error
```

**Comment by valdeirpsr** [comment]
For vitejs

1. Create file _vitest.setup.ts_

```typescript
import { vi } from "vitest";

/* @ts-ignore */
HTMLCanvasElement.prototype.getContext = () => {
  return {
    fillStyle: '',
    fillRect: vi.fn()
  }
}
```

2. Add in your _vitest.config.ts_

```javascript
export default defineConfig({
  test: {
    setupFiles: ['./vitest.setup.ts'],
  }
});
```

**Comment by kinoli** [comment]
This was needed for me in my `vitest.setup.ts` file.

```javascript
/* @ts-ignore */
HTMLCanvasElement.prototype.getContext = () => {
  return {
    fillStyle: '',
    fillRect: vi.fn(),
    clearRect: vi.fn(),
    scale: vi.fn(),
  }
}
```

**Comment by htutwaiphyoe** [comment]
> For vitejs
> 
> 1. Create file _vitest.setup.ts_
> 
> ```ts
> import { vi } from "vitest";
> 
> /* @ts-ignore */
> HTMLCanvasElement.prototype.getContext = () => {
>   return {
>     fillStyle: '',
>     fillRect: vi.fn()
>   }
> }
> ```
> 
> 2. Add in your _vitest.config.ts_
> 
> ```js
> export default defineConfig({
>   test: {
>     setupFiles: ['./vitest.setup.ts'],
>   }
> });
> ```

Work for me, Thanks.

**Comment by iDevBrandon** [comment]
after installing jest-canvas-mock, where should i add 

```js
{
  "jest": {
    "setupFiles": ["jest-canvas-mock"]
  }
}
```

in package.json?

**Comment by AlasdairWallaceMackie** [comment]
Adding the following to `jest-setup.js` fixed this issue for me:

```javascript
jest.mock('lottie-web', () => ({
  loadAnimation: jest.fn().mockImplementation(() => ({
    play: jest.fn(),
    destroy: jest.fn(),
    renderer: {
      ctx: {
        canvas: {
          getContext: jest.fn().mockReturnValue({
            fillStyle: null
          })
        }
      }
    }
  }))
}))
```

**Comment by gaurish-saini** [comment]
> For vitejs
> 
> 1. Create file _vitest.setup.ts_
> 
> import { vi } from "vitest";
> 
> /* @ts-ignore */
> HTMLCanvasElement.prototype.getContext = () => {
>   return {
>     fillStyle: '',
>     fillRect: vi.fn()
>   }
> }
> 2. Add in your _vitest.config.ts_
> 
> export default defineConfig({
>   test: {
>     setupFiles: ['./vitest.setup.ts'],
>   }
> });

Super, this worked for me!

**Comment by koriner** [comment]
I love how long this thread has been going. Good work team!

**Comment by srflp** [comment]
@AlasdairWallaceMackie for me 
```ts
jest.mock('lottie-web', () => ({}))
``` 
was just enough
